FIND_PATH(TCLCL_INCLUDE_DIR
        NAMES
        tclcl.h
        )

FIND_LIBRARY(TCLCL_LIBRARY
        NAMES
        tclcl
        )

find_program(TCLCL2CXX tcl2c++)

SET(TCLCL_INCLUDE_DIRS ${TCLCL_INCLUDE_DIR})
SET(TCLCL_LIBRARIES ${TCLCL_LIBRARY})

IF(TCLCL_INCLUDE_DIRS)
    MESSAGE(STATUS "TclCL include dirs set to ${TCLCL_INCLUDE_DIRS}")
ELSE(TCLCL_INCLUDE_DIRS)
    MESSAGE(FATAL " TclCL include dirs cannot be found")
ENDIF(TCLCL_INCLUDE_DIRS)

IF(TCLCL_LIBRARIES)
    MESSAGE(STATUS "TclCL library set to ${TCLCL_LIBRARIES}")
ELSE(TCLCL_LIBRARIES)
    MESSAGE(FATAL "TclCL library cannot be found")
ENDIF(TCLCL_LIBRARIES)

IF(TCLCL2CXX)
    MESSAGE(STATUS "tcl2c++ is found at ${TCLCL2CXX}")
ELSE(TCLCL2CXX)
    MESSAGE(FATAL "tcl2++ binary cannot be found")
ENDIF(TCLCL2CXX)

IF(TCLCL_INCLUDE_DIRS AND TCLCL_LIBRARIES)
    SET( PCAP_FOUND "YES" )
ENDIF(TCLCL_INCLUDE_DIRS AND TCLCL_LIBRARIES)


MARK_AS_ADVANCED(
        TCLCL_LIBRARIES
        TCLCL_INCLUDE_DIRS
)
