FIND_PATH(OTCL_INCLUDE_DIR
        NAMES
        otcl.h
        )

FIND_LIBRARY(OTCL_LIBRARY
        NAMES
        otcl
        )

SET(OTCL_INCLUDE_DIRS ${OTCL_INCLUDE_DIR})
SET(OTCL_LIBRARIES ${OTCL_LIBRARY})

IF(OTCL_INCLUDE_DIRS)
    MESSAGE(STATUS "Otcl include dirs set to ${OTCL_INCLUDE_DIRS}")
ELSE(OTCL_INCLUDE_DIRS)
    MESSAGE(FATAL " Otcl include dirs cannot be found")
ENDIF(OTCL_INCLUDE_DIRS)

IF(OTCL_LIBRARIES)
    MESSAGE(STATUS "OTCL library set to ${OTCL_LIBRARIES}")
ELSE(OTCL_LIBRARIES)
    MESSAGE(FATAL "OTCL library cannot be found")
ENDIF(OTCL_LIBRARIES)

IF(OTCL_INCLUDE_DIRS AND OTCL_LIBRARIES)
    SET( PCAP_FOUND "YES" )
ENDIF(OTCL_INCLUDE_DIRS AND OTCL_LIBRARIES)


MARK_AS_ADVANCED(
        OTCL_LIBRARIES
        OTCL_INCLUDE_DIRS
)
